// Code generated by confg. DO NOT EDIT.
// https://github.com/cheryl-chun/confgen

package test

import (
	"sync"

	"github.com/cheryl-chun/confgen/runtime"
)

var (
	instance *Config
	once     sync.Once
)

// Load 加载配置（单例模式，只会执行一次）
//
// 示例:
//
//	config.Load("config.yaml")
//	config.Load("config.yaml", config.WithEnv("APP_"))
func Load(path string, opts ...Option) error {
	var err error
	once.Do(func() {
		loader := runtime.NewLoader()
		loader.AddFile(path)

		// 应用选项
		for _, opt := range opts {
			opt.Apply(loader)
		}

		instance = &Config{}
		err = loader.Fill(instance)
	})
	return err
}

// Get 获取配置单例
//
// 必须先调用 Load() 初始化配置，否则会 panic
func Get() *Config {
	if instance == nil {
		panic("config not loaded, call Load() first")
	}
	return instance
}

// MustLoad 加载配置，失败时 panic
func MustLoad(path string, opts ...Option) {
	if err := Load(path, opts...); err != nil {
		panic(err)
	}
}

// Option 配置选项
type Option interface {
	Apply(*runtime.Loader)
}

type optionFunc func(*runtime.Loader)

func (f optionFunc) Apply(l *runtime.Loader) {
	f(l)
}

// WithEnv 添加环境变量配置源
//
// 示例: WithEnv("APP_") 会将 APP_SERVER_HOST 映射到 server.host
func WithEnv(prefix string) Option {
	return optionFunc(func(l *runtime.Loader) {
		l.AddEnv(prefix)
	})
}

type Config struct {
	App      AppConfig      `json:"app" yaml:"app" mapstructure:"app"`
	Server   ServerConfig   `json:"server" yaml:"server" mapstructure:"server"`
	Database DatabaseConfig `json:"database" yaml:"database" mapstructure:"database"`
	Cache    CacheConfig    `json:"cache" yaml:"cache" mapstructure:"cache"`
	Features FeaturesConfig `json:"features" yaml:"features" mapstructure:"features"`

	// ConfigTree 内嵌的配置树，用于动态查询（由 runtime 自动填充）
	ConfigTree *runtime.Tree
}

type AppConfig struct {
	Name     string `json:"name" yaml:"name" mapstructure:"name"`
	Version  string `json:"version" yaml:"version" mapstructure:"version"`
	LogLevel string `json:"log_level" yaml:"log_level" mapstructure:"log_level"`
}

type CacheConfig struct {
	RedisPort  int    `json:"redis_port" yaml:"redis_port" mapstructure:"redis_port"`
	TtlSeconds int    `json:"ttl_seconds" yaml:"ttl_seconds" mapstructure:"ttl_seconds"`
	RedisHost  string `json:"redis_host" yaml:"redis_host" mapstructure:"redis_host"`
}

type DatabaseConfig struct {
	User     string `json:"user" yaml:"user" mapstructure:"user"`
	Password string `json:"password" yaml:"password" mapstructure:"password"`
	Dbname   string `json:"dbname" yaml:"dbname" mapstructure:"dbname"`
	PoolSize int    `json:"pool_size" yaml:"pool_size" mapstructure:"pool_size"`
	Driver   string `json:"driver" yaml:"driver" mapstructure:"driver"`
	Host     string `json:"host" yaml:"host" mapstructure:"host"`
	Port     int    `json:"port" yaml:"port" mapstructure:"port"`
}

type FeaturesConfig struct {
	EnableMetrics bool `json:"enable_metrics" yaml:"enable_metrics" mapstructure:"enable_metrics"`
	EnableTracing bool `json:"enable_tracing" yaml:"enable_tracing" mapstructure:"enable_tracing"`
	RateLimitRps  int  `json:"rate_limit_rps" yaml:"rate_limit_rps" mapstructure:"rate_limit_rps"`
}

type ServerConfig struct {
	Port       int    `json:"port" yaml:"port" mapstructure:"port"`
	TimeoutMs  int    `json:"timeout_ms" yaml:"timeout_ms" mapstructure:"timeout_ms"`
	SSLEnabled bool   `json:"ssl_enabled" yaml:"ssl_enabled" mapstructure:"ssl_enabled"`
	Host       string `json:"host" yaml:"host" mapstructure:"host"`
}

// Set 动态设置配置值（自动推断值类型）
func (c *Config) Set(path string, value interface{}, source runtime.SourceType) error {
	if c.ConfigTree == nil {
		return nil
	}
	return c.ConfigTree.Set(path, value, source)
}

// Watch 监听指定 path 的值变化
func (c *Config) Watch(path string, callback runtime.WatchCallback) func() {
	if c.ConfigTree == nil {
		return func() {}
	}
	return c.ConfigTree.Watch(path, callback)
}

// GetString 动态查询字符串值
//
// 示例: cfg.GetString("server.host")
func (c *Config) GetString(path string) string {
	if c.ConfigTree == nil {
		return ""
	}
	return c.ConfigTree.GetString(path)
}

// GetInt 动态查询整数值
func (c *Config) GetInt(path string) int {
	if c.ConfigTree == nil {
		return 0
	}
	return c.ConfigTree.GetInt(path)
}

// GetBool 动态查询布尔值
func (c *Config) GetBool(path string) bool {
	if c.ConfigTree == nil {
		return false
	}
	return c.ConfigTree.GetBool(path)
}

// GetFloat 动态查询浮点数值
func (c *Config) GetFloat(path string) float64 {
	if c.ConfigTree == nil {
		return 0
	}
	return c.ConfigTree.GetFloat(path)
}

// Get 动态查询配置值（返回 interface{}）
func (c *Config) Get(path string) interface{} {
	if c.ConfigTree == nil {
		return nil
	}
	return c.ConfigTree.Get(path)
}
