package test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/cheryl-chun/confgen/internal/generate"
)

// TestEndToEnd 端到端测试：从 YAML 文件到生成 Go 代码
func TestEndToEnd(t *testing.T) {
	// 准备测试配置文件
	yamlContent := `
server:
  host: "localhost"
  port: 8080
  timeout: 30.5
  enabled: true
  tags:
    - "production"
    - "web"

database:
  host: "db.example.com"
  port: 5432
  max_connections: 100
  credentials:
    username: "admin"
    password: "secret"

api:
  base_url: "https://api.example.com"
  api_key: "secret-key"
  timeout: 10
`

	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, "config.yaml")
	outputPath := filepath.Join(tmpDir, "config_gen.go")

	// 写入测试配置
	if err := os.WriteFile(configPath, []byte(yamlContent), 0644); err != nil {
		t.Fatalf("Failed to write test config: %v", err)
	}

	// 执行代码生成
	opts := generate.Options{
		InputPath:   configPath,
		OutputPath:  outputPath,
		PackageName: "config",
		WatchMode:   false,
		DryRun:      false,
	}

	err := generate.Run(opts)
	if err != nil {
		t.Fatalf("generate.Run failed: %v", err)
	}

	// 读取生成的代码
	generated, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("Failed to read generated file: %v", err)
	}

	code := string(generated)
	t.Log("Generated code:")
	t.Log(code)

	// 验证生成的代码
	t.Run("Header", func(t *testing.T) {
		mustContain(t, code, "// Code generated by confg. DO NOT EDIT.")
		mustContain(t, code, "package config")
	})

	t.Run("RootStruct", func(t *testing.T) {
		mustContain(t, code, "type Config struct")
		mustContain(t, code, "Server")
		mustContain(t, code, "Database")
		mustContain(t, code, "API")
	})

	t.Run("NestedStructs", func(t *testing.T) {
		mustContain(t, code, "type ServerConfig struct")
		mustContain(t, code, "type DatabaseConfig struct")
		mustContain(t, code, "type APIConfig struct")
		mustContain(t, code, "type CredentialsConfig struct")
	})

	t.Run("FieldTypes", func(t *testing.T) {
		mustContain(t, code, "Host")
		mustContain(t, code, "string")
		mustContain(t, code, "Port")
		mustContain(t, code, "int")
		mustContain(t, code, "Timeout")
		mustContain(t, code, "float64")
		mustContain(t, code, "Enabled")
		mustContain(t, code, "bool")
		mustContain(t, code, "Tags")
		mustContain(t, code, "[]string")
	})

	t.Run("StructTags", func(t *testing.T) {
		mustContain(t, code, `json:"host"`)
		mustContain(t, code, `yaml:"port"`)
		mustContain(t, code, `mapstructure:"max_connections"`)
	})

	t.Run("NamingConventions", func(t *testing.T) {
		// snake_case → PascalCase
		mustContain(t, code, "MaxConnections")
		mustContain(t, code, "BaseURL")  // base_url → BaseURL
		mustContain(t, code, "APIKey")   // api_key → APIKey (API 全大写)
	})

	// 验证生成的代码可以被编译
	t.Run("Compilation", func(t *testing.T) {
		// 注意：这只是检查语法，不实际编译
		// 可以使用 go/parser 或 go/ast 进行更严格的验证
		if !strings.Contains(code, "type Config struct") {
			t.Error("Generated code is incomplete")
		}
	})
}

// TestDryRunMode 测试 dry-run 模式
func TestDryRunMode(t *testing.T) {
	yamlContent := `
app:
  name: "myapp"
  version: "1.0.0"
`

	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, "config.yaml")

	if err := os.WriteFile(configPath, []byte(yamlContent), 0644); err != nil {
		t.Fatalf("Failed to write test config: %v", err)
	}

	// Dry run 模式 - 不写入文件
	opts := generate.Options{
		InputPath:   configPath,
		OutputPath:  "ignored.go",
		PackageName: "main",
		DryRun:      true,
	}

	// 捕获输出不太容易，这里只验证不报错
	err := generate.Run(opts)
	if err != nil {
		t.Fatalf("generate.Run failed: %v", err)
	}

	// 验证没有创建文件
	if _, err := os.Stat("ignored.go"); !os.IsNotExist(err) {
		t.Error("Dry run should not create output file")
	}
}

// TestJSONInput 测试 JSON 输入
func TestJSONInput(t *testing.T) {
	jsonContent := `{
  "server": {
    "host": "localhost",
    "port": 8080
  },
  "database": {
    "host": "db.example.com",
    "port": 5432
  }
}`

	tmpDir := t.TempDir()
	configPath := filepath.Join(tmpDir, "config.json")
	outputPath := filepath.Join(tmpDir, "config_gen.go")

	if err := os.WriteFile(configPath, []byte(jsonContent), 0644); err != nil {
		t.Fatalf("Failed to write test config: %v", err)
	}

	opts := generate.Options{
		InputPath:   configPath,
		OutputPath:  outputPath,
		PackageName: "main",
	}

	err := generate.Run(opts)
	if err != nil {
		t.Fatalf("generate.Run failed: %v", err)
	}

	// 读取生成的代码
	generated, err := os.ReadFile(outputPath)
	if err != nil {
		t.Fatalf("Failed to read generated file: %v", err)
	}

	code := string(generated)
	t.Log("Generated code from JSON:")
	t.Log(code)

	// 验证
	mustContain(t, code, "type Config struct")
	mustContain(t, code, "type ServerConfig struct")
	mustContain(t, code, "type DatabaseConfig struct")
}

// mustContain 验证字符串包含指定内容
func mustContain(t *testing.T, s, substr string) {
	t.Helper()
	if !strings.Contains(s, substr) {
		t.Errorf("Generated code does not contain %q", substr)
	}
}