package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"slices"

	"github.com/cheryl-chun/confgen/internal/analyzer"
)

// Generator implements a buffer-driven engine for rendering Go source code
// based on inferred structural metadata.
type Generator struct {
	opts Options
	buf  *bytes.Buffer
}

// NewGenerator initializes a code generator with specified options and
// an internal buffer for efficient string concatenation.
func NewGenerator(opts Options) *Generator {
	return &Generator{
		opts: opts,
		buf:  &bytes.Buffer{},
	}
}

// Generate orchestrates the multi-stage rendering pipeline to produce
// formatted Go source code. The process follows a strict sequence:
// 1. Header emission
// 2. Package declaration
// 3. Import and singleton logic injection
// 4. Primary and auxiliary struct rendering
// 5. Dynamic method generation
// 6. Canonical syntax formatting via go/format.
func (g *Generator) Generate(result *analyzer.AnalyzeResult) (string, error) {
	// 1. Emit standard file header and "DO NOT EDIT" warning.
	g.writeHeader()

	// 2. Inject package identifier.
	g.writePackage()

	// 3. Generate boilerplate for singletons and lifecycle management.
	singletonCode, err := g.generateSingletonCodeWithTemplate(result)
	if err != nil {
		return "", fmt.Errorf("failed to generate singleton code: %w", err)
	}
	g.buf.WriteString(singletonCode)

	// 4. Render the primary configuration entry-point (Root Struct).
	if result.RootStruct != nil {
		g.writeStructWithTree(result.RootStruct, true)
		g.buf.WriteString("\n")
	}

	// 5. Render auxiliary struct definitions.
	// Ensure deterministic output by sorting struct names alphabetically.
	structNames := make([]string, 0, len(result.SubStructs))
	for name := range result.SubStructs {
		structNames = append(structNames, name)
	}
	slices.Sort(structNames)

	for _, name := range structNames {
		structDef := result.SubStructs[name]
		g.writeStructWithTree(structDef, false)
		g.buf.WriteString("\n")
	}

	// 6. Generate methods for dynamic schema traversal and querying.
	dynamicMethods, err := g.generateDynamicMethodsWithTemplate(result)
	if err != nil {
		return "", fmt.Errorf("failed to generate dynamic methods: %w", err)
	}
	g.buf.WriteString(dynamicMethods)

	// 7. Perform final syntax canonicalization and formatting.
	formatted, err := g.formatCode()
	if err != nil {
		// Return unformatted raw buffer alongside the error for debugging purposes.
		return g.buf.String(), fmt.Errorf("failed to format code: %w", err)
	}

	return formatted, nil
}

// writeHeader emits a standard generator warning to notify users that
// manual modifications will be overwritten.
func (g *Generator) writeHeader() {
	g.buf.WriteString("// Code generated by confgen. DO NOT EDIT.\n")
	g.buf.WriteString("// https://github.com/cheryl-chun/confgen\n\n")
}

// writePackage injects the user-defined package name into the source buffer.
func (g *Generator) writePackage() {
	g.buf.WriteString("package ")
	g.buf.WriteString(g.opts.PackageName)
	g.buf.WriteString("\n\n")
}

// formatCode applies standard Go syntax formatting (gofmt) to the raw buffer.
func (g *Generator) formatCode() (string, error) {
	formatted, err := format.Source(g.buf.Bytes())
	if err != nil {
		return "", err
	}
	return string(formatted), nil
}

// Generate is a high-level package helper that abstracts the generator's
// instantiation and execution for a given inference result.
func Generate(result *analyzer.AnalyzeResult, opts Options) (string, error) {
	gen := NewGenerator(opts)
	return gen.Generate(result)
}
