package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"slices"
	"strings"

	"github.com/cheryl-chun/confgen/internal/analyzer"
)

// Generator 代码生成器
type Generator struct {
	opts Options
	buf  *bytes.Buffer
}

// NewGenerator 创建代码生成器
func NewGenerator(opts Options) *Generator {
	return &Generator{
		opts: opts,
		buf:  &bytes.Buffer{},
	}
}

// Generate 生成 Go 源码
//
// 流程:
// 1. 写入文件头注释
// 2. 写入 package 声明
// 3. 写入导入语句
// 4. 写入单例变量和函数
// 5. 写入根 struct（包含 tree 字段）
// 6. 写入所有嵌套 struct
// 7. 写入动态查询方法
// 8. 格式化代码
func (g *Generator) Generate(result *analyzer.AnalyzeResult) (string, error) {
	// 1. 文件头注释
	g.writeHeader()

	// 2. package 声明
	g.writePackage()

	// 3. 写入导入语句和单例代码
	singletonCode, err := g.generateSingletonCodeWithTemplate(result)
	if err != nil {
		return "", fmt.Errorf("failed to generate singleton code: %w", err)
	}
	g.buf.WriteString(singletonCode)

	// 4. 写入根 struct（包含 tree 字段）
	if result.RootStruct != nil {
		g.writeStructWithTree(result.RootStruct, true)
		g.buf.WriteString("\n")
	}

	// 5. 写入所有嵌套 struct
	// 按名称排序，保证输出稳定
	structNames := make([]string, 0, len(result.SubStructs))
	for name := range result.SubStructs {
		structNames = append(structNames, name)
	}
	// 简单排序
	slices.Sort(structNames)

	for _, name := range structNames {
		structDef := result.SubStructs[name]
		g.writeStructWithTree(structDef, false)
		g.buf.WriteString("\n")
	}

	// 6. 写入动态查询方法
	dynamicMethods, err := g.generateDynamicMethodsWithTemplate(result)
	if err != nil {
		return "", fmt.Errorf("failed to generate dynamic methods: %w", err)
	}
	g.buf.WriteString(dynamicMethods)

	// 7. 格式化代码
	formatted, err := g.formatCode()
	if err != nil {
		// 如果格式化失败，返回原始代码和错误
		return g.buf.String(), fmt.Errorf("failed to format code: %w", err)
	}

	return formatted, nil
}

// writeHeader 写入文件头注释
func (g *Generator) writeHeader() {
	g.buf.WriteString("// Code generated by confg. DO NOT EDIT.\n")
	g.buf.WriteString("// https://github.com/cheryl-chun/confgen\n\n")
}

// writePackage 写入 package 声明
func (g *Generator) writePackage() {
	g.buf.WriteString("package ")
	g.buf.WriteString(g.opts.PackageName)
	g.buf.WriteString("\n\n")
}

// writeStruct 写入一个 struct 定义
func (g *Generator) writeStruct(def *analyzer.StructDef) {
	g.writeStructWithTree(def, false)
}

// writeStructWithTree 写入一个 struct 定义（可选包含 tree 字段）
func (g *Generator) writeStructWithTree(def *analyzer.StructDef, includeTree bool) {
	if def == nil {
		return
	}

	// struct 声明
	g.buf.WriteString("type ")
	g.buf.WriteString(def.Name)
	g.buf.WriteString(" struct {\n")

	// 计算字段对齐
	maxNameLen := 0
	maxTypeLen := 0
	for _, field := range def.Fields {
		if len(field.Name) > maxNameLen {
			maxNameLen = len(field.Name)
		}
		if len(field.Type) > maxTypeLen {
			maxTypeLen = len(field.Type)
		}
	}

	// 如果需要包含 ConfigTree 字段，也计算其长度
	if includeTree {
		if len("ConfigTree") > maxNameLen {
			maxNameLen = len("ConfigTree")
		}
		treeType := "*tree.ConfigTree"
		if len(treeType) > maxTypeLen {
			maxTypeLen = len(treeType)
		}
	}

	// 写入普通字段
	for _, field := range def.Fields {
		g.writeField(field, maxNameLen, maxTypeLen)
	}

	// 写入 tree 字段（如果是根 struct）
	if includeTree {
		g.buf.WriteString("\n")
		g.buf.WriteString("\t// ConfigTree 内嵌的配置树，用于动态查询（由 runtime 自动填充）\n")
		g.buf.WriteString("\tConfigTree")
		padding := maxNameLen - len("ConfigTree") + 1
		g.buf.WriteString(strings.Repeat(" ", padding))
		g.buf.WriteString("*tree.ConfigTree")
		g.buf.WriteString("\n")
	}

	g.buf.WriteString("}\n")
}

// writeField 写入一个字段
func (g *Generator) writeField(field *analyzer.FieldDef, maxNameLen, maxTypeLen int) {
	// 字段名
	g.buf.WriteString("\t")
	g.buf.WriteString(field.Name)

	// 对齐空格
	padding := maxNameLen - len(field.Name) + 1
	g.buf.WriteString(strings.Repeat(" ", padding))

	// 字段类型
	g.buf.WriteString(field.Type)

	// 对齐 tags
	padding = maxTypeLen - len(field.Type) + 1
	g.buf.WriteString(strings.Repeat(" ", padding))

	// struct tags
	g.buf.WriteString("`")
	g.writeStructTags(field)
	g.buf.WriteString("`")

	// 注释 (可选)
	if g.opts.AddComments && field.Comment != "" {
		g.buf.WriteString(" // ")
		g.buf.WriteString(field.Comment)
	}

	g.buf.WriteString("\n")
}

// writeStructTags 写入 struct tags
func (g *Generator) writeStructTags(field *analyzer.FieldDef) {
	tags := []string{}

	if field.JSONTag != "" {
		tags = append(tags, fmt.Sprintf(`json:"%s"`, field.JSONTag))
	}

	if field.YAMLTag != "" {
		tags = append(tags, fmt.Sprintf(`yaml:"%s"`, field.YAMLTag))
	}

	if field.MapStructTag != "" {
		tags = append(tags, fmt.Sprintf(`mapstructure:"%s"`, field.MapStructTag))
	}

	g.buf.WriteString(strings.Join(tags, " "))
}

// formatCode 格式化生成的代码
func (g *Generator) formatCode() (string, error) {
	formatted, err := format.Source(g.buf.Bytes())
	if err != nil {
		return "", err
	}
	return string(formatted), nil
}

// Generate 是包级别的便捷函数
func Generate(result *analyzer.AnalyzeResult, opts Options) (string, error) {
	gen := NewGenerator(opts)
	return gen.Generate(result)
}