package generate

import (
	"fmt"
	"os"

	"github.com/cheryl-chun/confgen/internal/parser"
)

// Run 执行代码生成
func Run(opts Options) error {
	// 1. 验证选项
	if err := opts.Validate(); err != nil {
		return fmt.Errorf("invalid options: %w", err)
	}

	// 2. 检查输入文件是否存在
	if _, err := os.Stat(opts.InputPath); os.IsNotExist(err) {
		return fmt.Errorf("%w: %s", ErrFileNotFound, opts.InputPath)
	}

	// 3. 使用工厂模式获取解析器并解析文件
	fmt.Printf("[1/4] Parsing config file: %s\n", opts.InputPath)

	result, err := parser.ParseFile(opts.InputPath)
	if err != nil {
		if err == parser.ErrParserNotFound || err == parser.ErrUnsupportedFormat {
			return fmt.Errorf("%w: %s (supported: %v)",
				ErrUnsupportedFileType, opts.InputPath, parser.SupportedFormats())
		}
		return fmt.Errorf("failed to parse config: %w", err)
	}

	fmt.Printf("     ✓ Parsed successfully (root has %d fields)\n", len(result.Root.Children))

	// 4. 类型推断和分析
	// TODO: 调用 analyzer 包进行类型推断
	fmt.Printf("[2/4] Analyzing types...\n")
	fmt.Printf("     ⚠ Type inference not yet implemented\n")

	// 5. 生成代码
	// TODO: 调用 codegen 包生成代码
	fmt.Printf("[3/4] Generating code...\n")
	fmt.Printf("     ⚠ Code generation not yet implemented\n")

	// 6. 输出结果
	if opts.DryRun {
		// 打印到 stdout
		fmt.Printf("[4/4] Output mode: stdout\n")
		fmt.Println("\n// Code generated by confg. DO NOT EDIT.")
		fmt.Printf("package %s\n\n", opts.PackageName)
		fmt.Println("// TODO: 生成的代码将在这里显示")
	} else {
		// 写入文件
		fmt.Printf("[4/4] Writing to: %s\n", opts.OutputPath)
		fmt.Printf("     ⚠ File writing not yet implemented\n")
	}

	fmt.Println("\n✓ Generation completed successfully!")
	fmt.Println("  Note: Parser is working, but type inference and code generation are not yet implemented.")
	return nil
}